apiVersion: v1
kind: Service
metadata:
  name: "{{ include "moon.fullname" . }}-cat-facts"
  labels:
    {{- include "moon.cat.labels" . | nindent 4 }}
spec:
  type: {{ .Values.facts.service.type }}
  ports:
    - port: {{ .Values.facts.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "moon.cat.selectorLabels" . | nindent 4 }}
