apiVersion: v1
kind: Service
metadata:
  name: "{{ include "moon.fullname" . }}-time"
  labels:
    {{- include "moon.time.labels" . | nindent 4 }}
spec:
  type: {{ .Values.time.service.type }}
  ports:
    - port: {{ .Values.time.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "moon.time.selectorLabels" . | nindent 4 }}
