apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-stg-01
  region: us-east-1
  version: "1.19"

availabilityZones:
  - us-east-1a
  - us-east-1b

managedNodeGroups:
  - name: eks-stg-01
    instanceType: t3.medium
    minSize: 2
    maxSize: 4
    desiredCapacity: 2
    volumeSize: 120
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key

